services:
  file_monitor:
    build: .
    volumes:
      - type: bind
        source: ${HOST_FOLDER}
        target: /app/target
        read_only: false
    env_file:
      - .env
    environment:
      - MONITOR_DIR=target
      - PYTHONUNBUFFERED=1